# Generated by Django 5.2.3 on 2025-08-17 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='chapa_status_text',
            field=models.CharField(blank=True, help_text="Chapa's payment status as reported by Chapa.", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='chapa_transaction_id',
            field=models.CharField(blank=True, help_text="Chapa's unique transaction identifier (tx_ref or transaction_id).", max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Canceled'), ('REVERSED', 'Reversed')], default='PENDING', help_text="Chapa's payment status as reported by Chapa.", max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('chapa', 'Chapa Payment Gateway'), ('credit_card', 'Credit Card'), ('paypal', 'PayPal'), ('stripe', 'Stripe')], default='chapa', help_text='The payment method or gateway used.', max_length=20),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['chapa_transaction_id'], name='listings_pa_chapa_t_282047_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='listings_pa_status_98563c_idx'),
        ),
    ]
